import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f3f4f6",
  },
  mapContainer: {
    flex: 1,
    position: "relative",
  },
  map: {
    width: "100%",
    height: "100%",
  },
  customMarker: {
    alignItems: "center",
    justifyContent: "center",
  },
  participantBadge: {
    position: "absolute",
    top: -4,
    right: -8,
    width: 24,
    height: 24,
    backgroundColor: "white",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#7B68EE",
    alignItems: "center",
    justifyContent: "center",
  },
  participantCount: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#7B68EE",
  },
  topControls: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    flexDirection: "row",
    gap: 12,
  },
  filterControlButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "white",
    paddingVertical: 12,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  filterControlText: {
    fontSize: 14,
    color: "#111827",
  },
  navigationButton: {
    width: 48,
    height: 48,
    backgroundColor: "#7B68EE",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  detailsCard: {
    position: "absolute",
    bottom: 16,
    left: 16,
    right: 16,
    backgroundColor: "white",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  detailsContent: {
    marginBottom: 16,
  },
  categoryBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#f3e8ff",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 8,
  },
  categoryText: {
    fontSize: 12,
    color: "#7B68EE",
  },
  participantsText: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 8,
  },
  missionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 8,
  },
  distanceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  distanceText: {
    fontSize: 14,
    color: "#6b7280",
  },
  detailsActions: {
    flexDirection: "row",
    gap: 12,
  },
  viewDetailsButton: {
    flex: 1,
    backgroundColor: "#7B68EE",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  viewDetailsText: {
    color: "white",
    fontWeight: "600",
  },
  closeButton: {
    flex: 1,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  closeButtonText: {
    color: "#111827",
    fontWeight: "600",
  },
})